apiVersion: v1
kind: Service
metadata:
  name: { { include "bestrong-webapp.fullname" . } }
  labels:
    app: { { .Values.labels.app } }
    tier: { { .Values.labels.tier } }
spec:
  selector:
    app: { { .Values.labels.app } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.containerPort } }
  type: { { .Values.service.type } }
